spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/11c?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Nan12091209

  mvc:
    static-path-pattern: /**

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
